spring:
  datasource:
#    url: jdbc:h2:mem:testdb
    url: jdbc:h2:file:./hotel-db
    username: sa
    password: sa
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    check-template-location: true
    cache: false